version: '3.1'
services:
  postgresdb:
    container_name: postgresdb
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    volumes:
      - postgresdb:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgresdb
    restart: unless-stopped
  backend:
    container_name: awp-enterprise-automation
    image: awp/enterprise-automation
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgresdb:5432/postgres
      SPRING_LIQUIBASE_URL: jdbc:postgresql://postgresdb:5432/postgres
    ports:
      - "8080:8080"
    networks:
      - postgresdb
      - backend
    depends_on:
      - postgresdb
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
    ports:
      - '9090:9090'
    networks:
      - backend
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    ports:
      - '3000:3000'

networks:
  postgresdb:
    driver: bridge
  backend:
    driver: bridge

volumes:
  postgresdb:
  prometheus_data:
  grafana_data: